// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBittwGDcbKwZ4t2yN3SKoelEn94nZYPiI',
    appId: '1:30124424543:android:8cab8f194694c85050caea',
    messagingSenderId: '30124424543',
    projectId: 'passeport-nautique-de-l-estrie',
    storageBucket: 'passeport-nautique-de-l-estrie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkvVNKheallEyna3iBltg98gVGFkrkSPY',
    appId: '1:30124424543:ios:47b3672609cab21e50caea',
    messagingSenderId: '30124424543',
    projectId: 'passeport-nautique-de-l-estrie',
    storageBucket: 'passeport-nautique-de-l-estrie.appspot.com',
    androidClientId: '30124424543-cgfft9625ac107139gicqgplpd5qbupe.apps.googleusercontent.com',
    iosClientId: '30124424543-g8vc56l9776ies9l5na5gdvmhh8q6eih.apps.googleusercontent.com',
    iosBundleId: 'com.example.passeportNautiqueEstrie',
  );
}
